---
title: "Crime in Ten Largest US Metropolitan Areas (2011)"

date: "October 4, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, fig.align='center'}
suppressWarnings(library(leaflet))

us_cities <- data.frame(name = c("New York", 
                                 "Los Angeles", 
                                 "Chicago",
                                 "Dallas",
                                 "Houston",
                                 "Philadelphia",
                                 "Washington",
                                 "Miami",
                                 "Atlanta",
                                 "Boston"),
                             
                        pop = c(406.0,
                                405.4, 
                                304.8,
                                358.4,
                                550.8,
                                532.3,
                                334.6,
                                596.7,
                                400.9,
                                374.7),
                        lat = c(40.808611, 
                                34, 
                                41.9,
                                32.896944,
                                29.762778,
                                39.877,
                                38.886758,
                                26.133333,
                                33.8,
                                42.35817 ),
                        lng = c(-74.020386,
                                -118,
                                -87.65, 
                                -97.038056, 
                                -95.383056, 
                                -75.323, 
                                -77.041625, 
                                -80.2, 
                                -84.4, 
                                -71.06369),
                        comment=c(
                             "New York-Northern New Jersey-Long Island, NY-NJ-PA MSA - 406.0 per 100,000",
"Los Angeles-Long Beach-Santa Ana, CA MSA - 405.4 per 100,000",
"Chicago-Joliet-Naperville, IL-IN-WI MSA - 304.8 per 100,000 (excl. rape)",
"Dallas-Fort Worth-Arlington, TX MSA - 358.4 per 100,000",
"Houston-Sugar Land-Baytown, TX MSA - 550.8 per 100,000",
"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA - 532.3 per 100,000",
"Washington-Arlington-Alexandria, DC-VA-MD-WV MSA - 334.6 per 100,000",
"Miami-Fort Lauderdale-Pompano Beach, FL MSA - 596.7 per 100,000",
"Atlanta-Sandy Springs-Marietta, GA MSA - 400.9 per 100,000",
"Boston-Cambridge-Quincy, MA-NH MSA - 374.7 per 100,000"

))

qpal <- colorQuantile(
     palette = "YlOrRd", 
     domain=us_cities$pop, n = 4)


suppressMessages( us_cities %>%
     leaflet() %>%
     addTiles() %>%
     addMarkers(popup = us_cities$comment) %>%
     addCircles(weight = 3,opacity=.55, fillOpacity = .55, radius = (us_cities$pop) * 400, 
                color = ~qpal(us_cities$pop))%>%
     addLegend("bottomleft", pal = qpal, values = ~pop,
               title = "Violent Crime Rate Ranking, US Metropolitan Areas (Percentiles)",
               opacity = .55
     )%>% fitBounds(-118, 34, -71.06369,42.35817))
```
